apiVersion: v1
kind: Service
metadata:
  name: minio-secret
  labels:
    app: minio-secret
spec:
  clusterIP: None
  ports:
    - port: 9002
      name: minio-secret
  selector:
    app: minio-secret
