apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-hipster-front
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - shop.84.201.147.225.nip.io
    secretName: hipster-front
  rules:
  - host: shop.84.201.147.225.nip.io
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: {{ .Values.service.port }}

